export const authStyles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1rem',
    backgroundColor: '#f5f5f5',
  },
  formContainer: {
    width: '100%',
    maxWidth: '400px',
    backgroundColor: '#ffffff',
    padding: '3rem',
    borderRadius: '8px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  header: {
    textAlign: 'center',
    marginBottom: '2rem',
  },
  title: {
    fontSize: '1.75rem',
    fontWeight: 'bold',
    marginBottom: '0.75rem',
    color: '#1a1a1a',
  },
  subtitle: {
    fontSize: '0.875rem',
    color: '#666666',
    lineHeight: '1.5',
  },
  formGroup: {
    marginBottom: '1.5rem',
  },
  error: {
    padding: '0.75rem',
    fontSize: '0.875rem',
    color: '#dc2626',
    backgroundColor: '#fee2e2',
    borderRadius: '4px',
    marginBottom: '1.5rem',
    border: '1px solid #fecaca',
  },
  footer: {
    textAlign: 'center',
    fontSize: '0.875rem',
    marginTop: '1.5rem',
    padding: '1rem 0 0',
    borderTop: '1px solid #e5e5e5',
  },
  footerText: {
    color: '#666666',
  },
  link: {
    color: '#2563eb',
    textDecoration: 'none',
    marginLeft: '0.25rem',
  },
  input: {
    width: '100%',
    padding: '0.75rem',
    fontSize: '0.875rem',
    border: '1px solid #e5e5e5',
    borderRadius: '4px',
    backgroundColor: '#ffffff',
    color: '#1a1a1a',
  },
  label: {
    display: 'block',
    marginBottom: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#374151',
  },
  button: {
    width: '100%',
    padding: '0.75rem',
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#ffffff',
    backgroundColor: '#2563eb',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  buttonHover: {
    backgroundColor: '#1d4ed8',
  },
};
